export enum RuleId {
  Deal = 1,
  Draft,
  GiveDraftToNeighbor,
  PlaceUnitOnBoard,
  RevealBoards,
  PayDeployedUnits,
  DeployEffects,
  ChooseUnpaidUnits,
  War,
  Income,
  Build,
  AgeEffects,
  AgeUnitsDie,
  AgeUnitsAge,
  SaveUnitsWithMysticEffect,
  NextTurn, 
  EndGame, 
}
