export enum LocationType {
    PlayerUnitHand = 1,
    PlayerDraftHand,
    PlayerUnitBoard,
    PlayerBuildingHand,
    PlayerBuildingBoard,
    PlayerGoldStock,
    PlayerAidCard,
    AgeStock,
    GoldStock,
    Discard,
    Deck,
    Time,
    Score,
}
