import { getEnumValues } from '@gamepark/rules-api'

export enum Unit {
    Commander = 1,
    Militiaman,
    TimeMaster,
    Peddler,
    Rogue,
    Sculptor,
    Treefolk,
    Necromancer,
    Veteran,
    Miner,
    Woodcutter, 
    Dragon,
    Knight,
    Leviathan,
    Shapeshifter,
    CaveSpirit,
    Cook,
    MysticalHealer,
    MasterAlchemist,
    ForestSpirit,
    LandLord,
    Manticore,
    GiantSnake,
    GrandArchitect,
    Colossus,
    Cerberus,
    Farmer,
    Kraken,
    Demon,
    ForestChild,
    Ogre,
    Hunter,
    Blacksmith,
    RelicOfWisdom,
    WoodMerchant,
    Strategist,
    PalmReader,
    Archer,
    Golem,
    Salamander,
    Monkey,
    Adventurer,
}



export const units = getEnumValues(Unit)